An equals check was added in 2.08 of 21 December 2015 (commit 55e5daa371e3b21dbc333a4e8db586a26875c4db). It has the (unintended) side-effect that it prevents users from "mixing types" in the behavior part of the spec (this is rare) when checking liveness properties:
```tla

  ...

  Next ==
    \/ x' \in 1..100
    \/ x' = TRUE
    \/ x' = "abc"

  Prop ==
    <>[]TRUE \* Actual property doesn't matter.
```

Instead, it can causes a hard-to-debug exception (iff there are enough
successor states to cause collisions above):

  Error: TLC threw an unexpected exception.
  This was probably caused by an error in the spec or model.
  See the User Output or TLC Console for clues to what happened.
  The exception was a java.lang.RuntimeException
  : Attempted to check equality of string "" with non-string:
  FALSE

[Bug][TLC][Regression]